services:
  cv-portfolio:
    build: .
    ports:
      - "80:8000"
    restart: unless-stopped

  fpv-trick-detection:
    build: ./projects/fpv-trick-detection
    expose:
      - "8000"
  box-measurement:
    build: ./projects/box-measurement
    expose:
      - "8000"
